### ISSUE TITLE
(DeviceEvent) NetworkCallback was not registered.

### ISSUE THREAD

**Issue by soowon-kang** [woohyeok-choi/ABC-Logger#92]
2020-12-01 12:50:48.557 3860-10259/kaist.iclab.abclogger E/kaist.iclab.abclogger.collector.event.DeviceEventCollector: NetworkCallback was not registered
2020-12-01 12:50:48.558 3860-10259/kaist.iclab.abclogger W/System.err: java.lang.IllegalArgumentException: NetworkCallback was not registered
2020-12-01 12:50:48.558 3860-10259/kaist.iclab.abclogger W/System.err:     at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:50)
2020-12-01 12:50:48.558 3860-10259/kaist.iclab.abclogger W/System.err:     at android.net.ConnectivityManager.unregisterNetworkCallback(ConnectivityManager.java:4392)
2020-12-01 12:50:48.558 3860-10259/kaist.iclab.abclogger W/System.err:     at kaist.iclab.abclogger.collector.event.DeviceEventCollector.onStop(DeviceEventCollector.kt:607)
2020-12-01 12:50:48.558 3860-10259/kaist.iclab.abclogger W/System.err:     at kaist.iclab.abclogger.core.collector.AbstractCollector$stop$1.invokeSuspend(AbstractCollector.kt:154)
2020-12-01 12:50:48.558 3860-10259/kaist.iclab.abclogger W/System.err:     at kaist.iclab.abclogger.core.collector.AbstractCollector$stop$1.invoke(Unknown Source:10)
2020-12-01 12:50:48.558 3860-10259/kaist.iclab.abclogger W/System.err:     at kaist.iclab.abclogger.core.collector.AbstractCollector$launch$1.invokeSuspend(AbstractCollector.kt:203)
2020-12-01 12:50:48.558 3860-10259/kaist.iclab.abclogger W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2020-12-01 12:50:48.558 3860-10259/kaist.iclab.abclogger W/System.err:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
2020-12-01 12:50:48.558 3860-10259/kaist.iclab.abclogger W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
2020-12-01 12:50:48.558 3860-10259/kaist.iclab.abclogger W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
2020-12-01 12:50:48.558 3860-10259/kaist.iclab.abclogger W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
2020-12-01 12:50:48.558 3860-10259/kaist.iclab.abclogger W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by soowon-kang** [comment]
fixed in 0.9.9-iota
